name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}\\.nuget\\packages
      SOLUTION_FILE: .\\src\\ElgatoLightControlPlugin.sln
      SDK_TOOL_BIN: .\\tools\\LogiPluginSdkTools\\LogiPluginTool.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup DotNet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: src/**/packages.lock.json

      - name: Cache Plugin SDK Tools
        id: plugin-sdk-tools-cache
        uses: actions/cache@v4
        with:
          path: ./tools/LogiPluginSdkTools
          key: plugin-sdk-tools-${{ runner.os }}-${{ hashFiles('./tools/install-sdk.ps1') }}
          restore-keys: plugin-sdk-tools-${{ runner.os }}-

      - name: Setup Plugin SDK Tools
        if: ${{ steps.plugin-sdk-tools-cache.outputs.cache-hit != 'true' }}
        shell: pwsh
        run: .\\tools\\install-sdk.ps1

      - name: Build plugin
        shell: pwsh
        run: |
          dotnet restore --locked-mode "$env:SOLUTION_FILE"
          dotnet build "$env:SOLUTION_FILE" `
          --configuration="Release" `
          -p:Version=0.0.1.${{ github.run_number }}

      - name: Pack Plugin
        shell: pwsh
        run: |
          & "$env:SDK_TOOL_BIN" pack `
            -input=".\bin\Release\" `
            -output=".\dist\ElgatoLightControlPlugin.lplug4"

      - name: Verify Plugin
        shell: pwsh
        run: |
          & "$env:SDK_TOOL_BIN" verify `
          -path=".\dist\ElgatoLightControlPlugin.lplug4"

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ElgatoLightControlPlugin
          path: ./dist/ElgatoLightControlPlugin.lplug4
